### ISSUE TITLE
Change String to Text?

### ISSUE THREAD

**Issue by kozak** [parsonsmatt/servant-persistent#10]
Thanks a lot for your tutorials, they are awesome!  :1st_place_medal: 

Would it make sense to use Text instead of String in entity definitions, so that beginners like me, won't get tripped ?

**Comment by parsonsmatt** [comment]
That's a great idea! Would you like to put together a PR to accomplish that?

**Comment by StevenXL** [comment]
Are we talking about [this](https://github.com/parsonsmatt/servant-persistent/blob/master/src/Models.hs#L26-L30) the `User` entity to `Text` rather than `Strings`.

I only ask because I tried to literally replace `String` with `Text`, but I'd then have to install the [Data.Text](https://hackage.haskell.org/package/text-1.2.2.2/docs/Data-Text.html#t:Text) package. 

It sounded like this was a simpler change, so just wanted to verify if that is what is actually wanted.

**Comment by parsonsmatt** [comment]
Yup! That would be a good change to make.

To  install `Data.Text`, you'll want to add that dependency to the cabal file.

**Comment by parsonsmatt** [comment]
Thanks @StevenXL for fixing this!
