### ISSUE TITLE
Connexion string for production is not usable

### ISSUE THREAD

**Issue by Raveline** [parsonsmatt/servant-persistent#11]
I might be wrong, but the way you wrote the connexion string variable in [Config.hs](
https://github.com/parsonsmatt/servant-persistent/blob/master/src/Config.hs#L90):

`let prodStr = mconcat . zipWith (<>) keys $ BS.pack <$> envVars`

... will produce a string like : "host=myhostdbname=mydbnameuser=myuser..." rather than space-separated ("host=myhost dbname=mydbname user=myuser..."). A simple (though not very elegant) fix could be:

`let prodStr = mconcat . zipWith (<>) keys $ (flip BS.snoc ' ' . BS.pack) <$> envVars`

**Comment by parsonsmatt** [comment]
That's a great point, and I'm inclined to believe you. But the code was pulled from a service I actually did put out into production, and it did actually (somehow) work!

Instead of `mconcat`, which would make it `["asdf", "hello"] => "asdfhello"`, you would want to use `BS.intercalate " "`, which puts the `" "` between each element of the list: `["asdf", "hello"] => "asdf hello"`. That achieves basically the same thing as your code, but without the extra space at the end of the last variable in the sring.

**Comment by Raveline** [comment]
Damn, how could I forget about BS.intercalate ! Of course it's the way to do it, you're right !

I found the issue  while starting with your project to try something on my own "production-ish" server, so I can confirm that in some instances, it doesn't work. But there might be some odd psql settings that would make it work the way the code is, and that you have on your end - I'm no psql expert at all, so I can't say.

**Comment by naglalakk** [comment]
the connection string did not work for me either in Production mode. It's because the end result is a string without whitespace like @Raveline is describing and so it tries to look up a host with the value myhostdbname=mydbnameuser=myuser.. etc
My guess is that it worked in your production case because your env variables ended with a whitespace, this would work. I simply did
`let keys = [ "host=", " port=", " user=", " password=", " dbname="]` <= extra ' ' after host
Thank you for a very good project btw
