### ISSUE TITLE
[Question] Having a Dev environment for mocking data? 

### ISSUE THREAD

**Issue by Cmdv** [parsonsmatt/servant-persistent#45]
I've been trying to work out a way to mock data fetching (db/external api etc) when in a Dev mode.
The problem space is that one might have lots of external services so rather than develop against the live versions it would be great to have a flag to either fetch data or internally generated data.

What I can't quite work out is could  `AppT`'s `Config` be extended to hold a `isDev` value:

https://github.com/parsonsmatt/servant-persistent/blob/95df92b2fe9b0f421afa0cf1bcc9c3a4ca38b48c/src/Config.hs#L38-L44

https://github.com/parsonsmatt/servant-persistent/blob/95df92b2fe9b0f421afa0cf1bcc9c3a4ca38b48c/src/Config.hs#L50-L58

then at a function level case on `isDev` flag to determine wether to `maybeUser <- runDb (selectFirst [Md.UserName ==. str] [])` or `maybeGenUser <- getGenOfUser str`

https://github.com/parsonsmatt/servant-persistent/blob/95df92b2fe9b0f421afa0cf1bcc9c3a4ca38b48c/src/Api/User.hs#L47-L56

This doesn't feel right when you could probably utilise the `ReaderT` monad similarly to this example:

```
#!/usr/bin/env stack
-- stack --resolver lts-18.14 script
{-# LANGUAGE OverloadedStrings #-}
import RIO
import Prelude (putStrLn, print)

data App = App
  { appReadFile :: FilePath -> IO ByteString
  }

readFile' :: FilePath -> RIO App ByteString
readFile' fp = do
  app <- ask
  liftIO $ appReadFile app fp

fetchProd :: App
fetchProd = App { appReadFile = readFileBinary }

fetchMock :: App
fetchMock = App { appReadFile = \filepath -> pure $ encodeUtf8 $ "Fake contents of " <> fromString filepath }

main :: IO ()
main = do
  putStrLn "Mock version"
  runRIO fetchMock myProgram
  putStrLn "Real version"
  runRIO fetchProd myProgram

myProgram :: RIO App ()
myProgram = do
  fileText <- tryAny (readFile' "does-not-exist.txt") >>= liftIO . print
  ... -- continue with logic that handles what to do with `fileText`
```
The problem I can see with that example is you'd have to expand `App` for every different type of fetch you'd want to carry out and there would need to be 2 binaries of the app (which I don't mind tbf) so we know which "mode" the app is in.

But more importantly how could that pattern be implemented in the current context 🤔 

I understand this is probably totally out of context of this repo, but the way this example is structured feels like it could handle this feature in an easier manner. (Well that's the hope)

Any pointers would be greatly appreciated, failing that I will try to keep a thread going of my finding as I'm sure the ability to develop on non live data would be really useful. 😃

**Comment by Cmdv** [comment]
@parsonsmatt I ended up changing the fact that one has to `case` inside of the route function.

What we ended up is have 2 different binaries one for local and one for production. When the server is setup we pass in a type and stick it inside of `Config` for easy access via `ask`:

```haskell
data MyDataFetch = MyDataFetch
  { route1 :: a -> a
  , route2 :: a -> a
  ...
  }
```

This is slightly related but potentially not at all. The problem is I've been asked to use [Program](https://hackage.haskell.org/package/core-program-0.4.2.0) as a replacement or in conjunction with `AppT`.

The problem is that having a straight replacement isn't achievable due to `IO` being static in `Program`:
```
newtype Program τ α = Program (        ReaderT (Context τ) IO                     α )
newtype AppT m a    = AppT { runApp :: ReaderT Config     (ExceptT ServerError m) a }
```

My next thought was well maybe I can nest it inside of `AppT`
```
import Core.Program (Program, None)

-- in context
convertApp :: Config -> AppT (Program None) a -> Handler a
convertApp cfg appt = Handler $ runReaderT ( runApp $ appt) cfg

```
But I couldn't quite work out how to get access to the inner `ReaderT` to get out the `IO` 🤔

**Comment by and-pete** [comment]
> But I couldn't quite work out how to get access to the inner `ReaderT` to get out the `IO` 🤔

If you're just looking to hoist your Servant endpoint handlers from being in `Program τ`  to Servant's `Handler`, then the natural transformation below should help.
```haskell
import qualified Control.Exception.Safe as Safe
import Core.Program (Program, Context)
import Core.Program.Context (unProgram)
import Servant (Application, Handler(..), ServerError, ServerT)
import qualified Servant as S

-- | A natural transformation from `Program` to `Handler` (`servant`).
naturalTransformation :: Context τ -> Program τ a -> Handler a
naturalTransformation ctx
  = Handler
  . withExceptT toServerError
  . ExceptT
  . flip runReaderT ctx
  . unProgram
  . Safe.try

-- | Haven't looked too much into `core-program`'s error handling. But
-- an alternative to `withExceptT toServerError` & `Safe.try` might just
-- be `fmap Right` in their place.
toServerError
  :: SomeException
  -> ServerError 
toServerError _ = undefined

buildWaiApplication
  :: Context τ
  -> ServerT API (Program τ)    -- Note: These handlers are in the `Program τ` monad.
  -> Application
buildWaiApplication ctx routeHandlers =
  S.serve _API (S.hoistServer _API (naturalTransformation ctx) routeHandlers)

```
Hmm, though I'm not sure if there would be much to gain by stacking your `AppT m a` on top of `Program τ`. From what I gather, any additional context/state you want to carry around (other than the [many fields](https://github.com/aesiniath/unbeliever/blob/edf10e96eec9a6967ebb55d0d0b0372fb50f32cd/core-program/lib/Core/Program/Context.hs#L168-L187)) can just be done using the `τ` parameter in `Core.Program.Execute`'s `configure` function on program initialization.

And that covers the `ReaderT` aspect of your `AppT` type. For the errors & exceptions though, I'd need to dig further into `core-program` to get a better feel for how using `throwM` (from `Program τ`'s `MonadThrow` instance) route handlers would work out (vs `throwError`).

**Comment by and-pete** [comment]
> @and-pete thanks so much that's really helpful.
> 
> After looking at your code I've been now been trying to replace `AppT` with `Program`. But I'm stuck on making this instance:
> 
> ```haskell
> instance MonadError ServerError (Program a) where
>     throwError = Program . lift . throwError . _
>     -- :: ServerError -> IOException
>     catchError = _ 
>     -- :: Program a a1 -> (ServerError -> Program a a1) -> Program a a1
> ```
> 
> my brain hurts 😂

Hmmm, my suggestion would be to not write that instance until you know why you want/need it and what you expect it to do. And the implementation should follow from that (and not just what type checks). Error handling and exceptions can be tricky (at least, for me they can. ahah!). 

Questions I'd want to answer for myself if I was considering writing a `MonadError` instance `Program τ`:
  1)  Why do you _need_ a `MonadError` instance for what you are trying to achieve? Does `servant` require it?
  2)  Assuming for a moment that you do _need_ that `MonadError` instance, why is it for `ServerErrror` (from `servant`) and not say your own custom error sum type from your app?
  3) Given the `Program τ` has already has a `MonadThrow` and `MonadCatch` instance,  why did the `core-program` library author not include a `MonadError` instance as well for it? I can see that `mtl` is a dependency.
  4) Again given the `MonadThrow` and `MonadCatch` instances for `Program τ`, are there any circumstances where you would want the outcome of :
    a) `throwError` to result in a different behaviour than `Safe.throw` (e.g. should there be a difference between `Safe.throw err404` vs `throwError err404`)?
    b) `catchError` to behave differently than `Safe.catch`
    c) _IF_ the answer is no, can you just write:
```haskell
instance MonadError ServerError (Program τ) where
  throwError = Safe.throw
  catchError = Safe.catch
```
?
And if you can do that, why not just use `Safe.throw` and `Safe.catch` directly?

I haven't answered these questions for myself, but...

.... if you put a gun to my head.... my gut instinct would be that you don't need a `MonadError` instance for your handlers, especially if the `core-program` authors have chosen not to implement it.

And that if you used `curl` to test what happens when you `Safe.throw` the different `ServerError` types (`err401`, etc.) values in your `Program τ` handlers, you should find that they'll be correctly handled by `Servant`/`Warp`.

But beyond that, I'm really not sure how the other fancy exception handling & logging stuff that's going on in `core-program` would interact with Servant. I'd probably want to dive into some of the `core-program` repo's past issues & PRs around exceptions:
https://github.com/aesiniath/unbeliever/pull/62
https://github.com/aesiniath/unbeliever/pull/17
https://github.com/aesiniath/unbeliever/pull/6
https://github.com/aesiniath/unbeliever/issues/32
Seems like a cool library you've been asked to use though!

**Comment by Cmdv** [comment]
I'm going to close this as it's not related to this repo now, though it is still an interesting problem! 
I moved things over to https://github.com/Cmdv/servant-unbeliever-example incase people want to follow.

Thank you very much for the original help @parsonsmatt and for the great repo, I've really learnt a lot just from using it and all the great code comments 👍 👍
